name: .NET Tests
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v2
   - name: Setup .NET
     uses: actions/setup-dotnet@v3
     with:
       dotnet-version: '7.x'

   - name: Install Playwright
     run: pwsh ./PlaywrightFrameworkUpdate/src/PlaywrightFrameworkTest/bin/Debug/net6.0/playwright.ps1 install
       
   - name: Restore dependencies
     run: dotnet restore 
     
   - name: Build
     run: dotnet build 
      
   - name: Test
     run: dotnet test
     
   - name: Upload test results
     if: failure()
     uses: actions/upload-artifact@v2
     with:
       name: test-results
       path: '**/TestResults/*.trx'
