name: .NET Tests
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v2
   - name: Setup .NET
     uses: actions/setup-dotnet@v3
     with:
       dotnet-version: '7.x'
   - name: Restore dependencies
     run: dotnet restore PlaywrightFrameworkUpdate/PlaywrightFrameworkUpdate.sln
   - name: Build
     run: dotnet build --configuration Release PlaywrightFrameworkUpdate/PlaywrightFrameworkUpdate.sln
   - name: Test
     run: dotnet test --no-build --verbosity normal PlaywrightFrameworkUpdate/PlaywrightFrameworkUpdate.sln --logger:trx
   - name: Upload test results
     if: failure()
     uses: actions/upload-artifact@v2
     with:
       name: test-results
       path: '**/TestResults/*.trx'
